matrix:
  include:
    - language: java
      before_script: cd plugin
    - language: node_js
      node_js:
        - 12
      cache: yarn
      install: yarn --frozen-lockfile
      script: yarn check-packages
